"""Metadata database and object (file) store providers (docs/DESIGN.md §5, §6)."""

from __future__ import annotations

import asyncio
import os
import re
import shutil
import tempfile
import uuid
from collections.abc import AsyncIterator
from contextlib import AbstractAsyncContextManager, asynccontextmanager
from pathlib import Path
from typing import BinaryIO

from pydantic import BaseModel
from sqlalchemy.engine import URL
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.ext.asyncio import AsyncEngine, AsyncSession, async_sessionmaker

from ..db import migrate
from ..db.engine import create_engine, database_url, is_sqlite
from .base import HealthStatus, PlaceholderProvider, Provider, ProviderContext, ProviderHealth
from .registry import register


class MetadataDB(Provider):
    """Projects, documents, chats and messages (docs/DESIGN.md §3.9). Business logic (``app/services``) depends on
    this interface only: it opens a unit of work with ``session()`` and uses the models in ``app.db.models``."""

    capability = "metadata_db"

    def session(self) -> AbstractAsyncContextManager[AsyncSession]:
        """A unit of work: ``async with db.session() as s: …`` commits when the block succeeds and rolls back
        if it raises."""
        raise NotImplementedError(f"metadata_db provider {self.name!r} does not implement session()")


@register
class SqliteDB(MetadataDB):
    """SQLite through SQLAlchemy (aiosqlite). ``start()`` creates the directory and migrates the schema to head."""

    name = "sqlite"

    def __init__(self, config: BaseModel, ctx: ProviderContext) -> None:
        super().__init__(config, ctx)
        self._engine: AsyncEngine | None = None
        self._sessions: async_sessionmaker[AsyncSession] | None = None

    @property
    def url(self) -> URL:
        url = database_url(self.ctx.settings)
        if not is_sqlite(url):
            raise ValueError(f"metadata_db provider 'sqlite' needs a sqlite+aiosqlite:/// url, got {url.drivername}")
        return url

    @property
    def db_path(self) -> Path:
        return Path(self.url.database or "")

    async def start(self) -> None:
        url = self.url
        self.db_path.parent.mkdir(parents=True, exist_ok=True)
        await migrate.upgrade(url)
        self._engine = create_engine(url)
        self._sessions = async_sessionmaker(self._engine, expire_on_commit=False)

    async def close(self) -> None:
        if self._engine is not None:
            await self._engine.dispose()
        self._engine = self._sessions = None

    @asynccontextmanager
    async def _session(self) -> AsyncIterator[AsyncSession]:
        if self._sessions is None:
            raise RuntimeError("metadata_db is not started")
        async with self._sessions() as session, session.begin():
            yield session

    def session(self) -> AbstractAsyncContextManager[AsyncSession]:
        return self._session()

    async def health(self) -> ProviderHealth:
        where = _rel(self.db_path, self.ctx.settings.root_dir)
        if self._engine is None:
            return self._health(HealthStatus.DOWN, f"{where}: not started")
        try:
            async with self._engine.connect() as conn:
                revision = await migrate.current_revision(conn)
        except SQLAlchemyError as e:
            return self._health(HealthStatus.DOWN, f"{where}: {e}")
        return self._health(HealthStatus.OK, f"{where}, schema {revision}")


@register
class PostgresDB(MetadataDB, PlaceholderProvider):
    name = "postgres"


# Object keys: "/"-separated segments of letters, digits, ".", "_" and "-", each starting with a letter or digit, so a
# key can never be absolute, contain "..", or carry a user-supplied filename into a path.
_KEY_SEGMENT = r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}"
_KEY = re.compile(rf"{_KEY_SEGMENT}(?:/{_KEY_SEGMENT}){{0,15}}")
_COPY_CHUNK = 1024 * 1024


class ObjectNotFound(LookupError):
    """No object is stored under the key."""


def check_key(key: str) -> str:
    """Return ``key`` if it is a safe object key, else raise ValueError. Keys are generated by the app (e.g.
    ``<project_id>/<document_id>/v1.pdf``), never taken from an upload's filename."""
    if not isinstance(key, str) or len(key) > 1024 or not _KEY.fullmatch(key):
        raise ValueError(f"invalid object key {key!r}")
    return key


class ObjectStore(Provider):
    """Original uploaded files (docs/DESIGN.md §5, §6.3). Files are never passed between components as local paths:
    everything goes through this interface, and consumers that need a file on disk (Docling) get a temporary copy, so
    S3 is a drop-in replacement."""

    capability = "object_store"

    async def put(self, key: str, data: bytes | BinaryIO) -> int:
        """Store ``data`` (bytes, or a binary file object read from its current position) under ``key``, replacing
        any previous object. Returns the number of bytes stored."""
        raise NotImplementedError(f"{type(self).__name__}.put")

    async def get(self, key: str) -> bytes:
        """The object's content. Raises ObjectNotFound."""
        raise NotImplementedError(f"{type(self).__name__}.get")

    async def exists(self, key: str) -> bool:
        raise NotImplementedError(f"{type(self).__name__}.exists")

    def open_temp_copy(self, key: str, *, filename: str | None = None) -> AbstractAsyncContextManager[Path]:
        """``async with store.open_temp_copy(key) as path``: the object copied to a private temporary directory, named
        ``filename`` (a single safe key segment; default: the key's last segment). Removed when the block exits.
        Raises ObjectNotFound."""
        raise NotImplementedError(f"{type(self).__name__}.open_temp_copy")

    async def delete(self, key: str) -> bool:
        """Delete one object; True if it existed (a missing object is not an error)."""
        raise NotImplementedError(f"{type(self).__name__}.delete")

    async def delete_prefix(self, prefix: str) -> int:
        """Delete every object whose key is ``prefix`` or starts with ``prefix/``. Returns how many were deleted."""
        raise NotImplementedError(f"{type(self).__name__}.delete_prefix")


@register
class FilesystemStore(ObjectStore):
    """Objects as files under ``object_store.root``: key ``a/b/c.pdf`` → ``<root>/a/b/c.pdf``. Writes go to a temporary
    file in the same directory and are renamed into place, so a reader never sees a partial object."""

    name = "filesystem"

    @property
    def root(self) -> Path:
        root = self.config.root  # type: ignore[attr-defined]
        if not root:
            raise ValueError("object_store.root is required for the filesystem provider")
        return self.ctx.settings.path(root)

    async def start(self) -> None:
        self.root.mkdir(parents=True, exist_ok=True)

    def path_of(self, key: str) -> Path:
        """The file that holds ``key``; refuses anything that would resolve outside the root (e.g. via a symlink)."""
        root = self.root.resolve()
        path = (root / check_key(key)).resolve()
        if not path.is_relative_to(root) or path == root:
            raise ValueError(f"object key {key!r} resolves outside the store")
        return path

    async def put(self, key: str, data: bytes | BinaryIO) -> int:
        return await asyncio.to_thread(self._put_sync, self.path_of(key), data)

    async def get(self, key: str) -> bytes:
        path = self.path_of(key)
        try:
            return await asyncio.to_thread(path.read_bytes)
        except (FileNotFoundError, IsADirectoryError):
            raise ObjectNotFound(key) from None

    async def exists(self, key: str) -> bool:
        return self.path_of(key).is_file()

    @asynccontextmanager
    async def _temp_copy(self, key: str, filename: str | None) -> AsyncIterator[Path]:
        source = self.path_of(key)
        name = check_key(filename or source.name)
        if "/" in name:
            raise ValueError(f"temp copy filename must be a single segment, got {filename!r}")
        tmpdir = Path(await asyncio.to_thread(tempfile.mkdtemp, prefix="objcopy-"))
        try:
            target = tmpdir / name
            try:
                await asyncio.to_thread(shutil.copyfile, source, target)
            except (FileNotFoundError, IsADirectoryError):
                raise ObjectNotFound(key) from None
            yield target
        finally:
            await asyncio.to_thread(shutil.rmtree, tmpdir, True)

    def open_temp_copy(self, key: str, *, filename: str | None = None) -> AbstractAsyncContextManager[Path]:
        return self._temp_copy(key, filename)

    async def delete(self, key: str) -> bool:
        path = self.path_of(key)
        return await asyncio.to_thread(self._delete_sync, path)

    async def delete_prefix(self, prefix: str) -> int:
        path = self.path_of(prefix.rstrip("/"))
        return await asyncio.to_thread(self._delete_tree_sync, path)

    # -------------------------------------------------------------- blocking helpers (run in a thread)

    @staticmethod
    def _put_sync(path: Path, data: bytes | BinaryIO) -> int:
        path.parent.mkdir(parents=True, exist_ok=True)
        part = path.with_name(f".{path.name}.{uuid.uuid4().hex}.part")
        written = 0
        try:
            with part.open("wb") as out:
                if isinstance(data, bytes | bytearray | memoryview):
                    written = out.write(data)
                else:
                    while chunk := data.read(_COPY_CHUNK):
                        written += out.write(chunk)
                out.flush()
                os.fsync(out.fileno())
            os.replace(part, path)
        except BaseException:
            part.unlink(missing_ok=True)
            raise
        return written

    def _delete_sync(self, path: Path) -> bool:
        try:
            path.unlink()
        except FileNotFoundError:
            return False
        self._prune_empty_dirs(path.parent)
        return True

    def _delete_tree_sync(self, path: Path) -> int:
        if path.is_file():
            return int(self._delete_sync(path))
        if not path.is_dir():
            return 0
        count = sum(1 for p in path.rglob("*") if p.is_file())
        shutil.rmtree(path)
        self._prune_empty_dirs(path.parent)
        return count

    def _prune_empty_dirs(self, directory: Path) -> None:
        """Remove now-empty directories between an object and the root, so deleted projects leave no folders."""
        root = self.root.resolve()
        while directory != root and directory.is_relative_to(root):
            try:
                directory.rmdir()
            except OSError:  # not empty (or already gone)
                return
            directory = directory.parent

    async def health(self) -> ProviderHealth:
        root = self.root
        if not root.is_dir():
            return self._health(HealthStatus.DOWN, f"{root} does not exist")
        if not os.access(root, os.W_OK):
            return self._health(HealthStatus.DOWN, f"{root} is not writable")
        return self._health(HealthStatus.OK, f"{_rel(root, self.ctx.settings.root_dir)} writable")


@register
class S3Store(ObjectStore, PlaceholderProvider):
    name = "s3"


def _rel(path: Path, root: Path) -> str:
    try:
        return str(path.relative_to(root))
    except ValueError:
        return str(path)
